lang_mapping_library = {
    "aa": {"name": "Afar", "lcid": "4096"},
    "aa_DJ": {"name": "Afar (Djibouti)", "lcid": "4096"},
    "aa_ER": {"name": "Afar (Eritrea)", "lcid": "4096"},
    "aa_ET": {"name": "Afar (Ethiopia)", "lcid": "4096"},
    "af": {"name": "Afrikaans", "lcid": "54"},
    "af_NA": {"name": "Afrikaans (Namibia)", "lcid": "4096"},
    "af_ZA": {"name": "Afrikaans (South Africa)", "lcid": "1078"},
    "agq": {"name": "Aghem", "lcid": "4096"},
    "agq_CM": {"name": "Aghem (Cameroon)", "lcid": "4096"},
    "ak": {"name": "Akan", "lcid": "4096"},
    "ak_GH": {"name": "Akan (Ghana)", "lcid": "4096"},
    "sq": {"name": "Albanian", "lcid": "28"},
    "sq_AL": {"name": "Albanian (Albania)", "lcid": "1052"},
    "sq_MK": {"name": "Albanian (Macedonia FYRO)", "lcid": "4096"},
    "gsw": {"name": "Alsatian", "lcid": "132"},
    "gsw_FR": {"name": "Alsatian (France)", "lcid": "1156"},
    "gsw_LI": {"name": "Alsatian (Liechtenstein)", "lcid": "4096"},
    "gsw_CH": {"name": "Alsatian (Switzerland)", "lcid": "4096"},
    "am": {"name": "Amharic", "lcid": "94"},
    "am_ET": {"name": "Amharic (Ethiopia)", "lcid": "1118"},
    "ar": {"name": "Arabic", "lcid": "1"},
    "ar_DZ": {"name": "Arabic (Algeria)", "lcid": "5121"},
    "ar_BH": {"name": "Arabic (Bahrain)", "lcid": "15361"},
    "ar_TD": {"name": "Arabic (Chad)", "lcid": "4096"},
    "ar_KM": {"name": "Arabic (Comoros)", "lcid": "4096"},
    "ar_DJ": {"name": "Arabic (Djibouti)", "lcid": "4096"},
    "ar_EG": {"name": "Arabic (Egypt)", "lcid": "3073"},
    "ar_ER": {"name": "Arabic (Eritrea)", "lcid": "4096"},
    "ar_IQ": {"name": "Arabic (Iraq)", "lcid": "2049"},
    "ar_IL": {"name": "Arabic (Israel)", "lcid": "4096"},
    "ar_JO": {"name": "Arabic (Jordan)", "lcid": "11265"},
    "ar_KW": {"name": "Arabic (Kuwait)", "lcid": "13313"},
    "ar_LB": {"name": "Arabic (Lebanon)", "lcid": "12289"},
    "ar_LY": {"name": "Arabic (Libya)", "lcid": "4097"},
    "ar_MR": {"name": "Arabic (Mauritania)", "lcid": "4096"},
    "ar_MA": {"name": "Arabic (Morocco)", "lcid": "6145"},
    "ar_OM": {"name": "Arabic (Oman)", "lcid": "8193"},
    "ar_PS": {"name": "Arabic (Palestinian Authority)", "lcid": "4096"},
    "ar_QA": {"name": "Arabic (Qatar)", "lcid": "16385"},
    "ar_SA": {"name": "Arabic (Saudi Arabia)", "lcid": "1025"},
    "ar_SO": {"name": "Arabic (Somalia)", "lcid": "4096"},
    "ar_SS": {"name": "Arabic (South Sudan)", "lcid": "4096"},
    "ar_SD": {"name": "Arabic (Sudan)", "lcid": "4096"},
    "ar_SY": {"name": "Arabic (Syria)", "lcid": "10241"},
    "ar_TN": {"name": "Arabic (Tunisia)", "lcid": "7169"},
    "ar_AE": {"name": "Arabic (U.A.E.)", "lcid": "14337"},
    "ar_001": {"name": "Arabic (World)", "lcid": "4096"},
    "ar_YE": {"name": "Arabic (Yemen)", "lcid": "9217"},
    "hy": {"name": "Armenian", "lcid": "43"},
    "hy_AM": {"name": "Armenian (Armenia)", "lcid": "1067"},
    "as": {"name": "Assamese", "lcid": "77"},
    "as_IN": {"name": "Assamese (India)", "lcid": "1101"},
    "ast": {"name": "Asturian", "lcid": "4096"},
    "ast_ES": {"name": "Asturian (Spain)", "lcid": "4096"},
    "asa": {"name": "Asu", "lcid": "4096"},
    "asa_TZ": {"name": "Asu (Tanzania)", "lcid": "4096"},
    "az_Cyrl": {"name": "Azerbaijani (Cyrillic)", "lcid": "29740"},
    "az_Cyrl_AZ": {"name": "Azeri (Cyrillic Azerbaijan)", "lcid": "2092"},
    "az": {"name": "Azerbaijani (Latin)", "lcid": "44"},
    "az_Latn": {"name": "Azerbaijani (Latin)", "lcid": "30764"},
    "az_Latn_AZ": {"name": "Azeri (Latin Azerbaijan)", "lcid": "1068"},
    "ksf": {"name": "Bafia", "lcid": "4096"},
    "ksf_CM": {"name": "Bafia (Cameroon)", "lcid": "4096"},
    "bm": {"name": "Bamanankan", "lcid": "4096"},
    "bm_Latn_ML": {"name": "Bamanankan (Latin Mali)", "lcid": "4096"},
    "bn": {"name": "Bangla", "lcid": "69"},
    "bn_BD": {"name": "Bengali (Bangladesh)", "lcid": "2117"},
    "bn_IN": {"name": "Bengali (India)", "lcid": "1093"},
    "bas": {"name": "Basaa", "lcid": "4096"},
    "bas_CM": {"name": "Basaa (Cameroon)", "lcid": "4096"},
    "ba": {"name": "Bashkir", "lcid": "109"},
    "ba_RU": {"name": "Bashkir (Russia)", "lcid": "1133"},
    "eu": {"name": "Basque", "lcid": "45"},
    "eu_ES": {"name": "Basque (Basque)", "lcid": "1069"},
    "be": {"name": "Belarusian", "lcid": "35"},
    "be_BY": {"name": "Belarusian (Belarus)", "lcid": "1059"},
    "bem": {"name": "Bemba", "lcid": "4096"},
    "bem_ZM": {"name": "Bemba (Zambia)", "lcid": "4096"},
    "bez": {"name": "Bena", "lcid": "4096"},
    "bez_TZ": {"name": "Bena (Tanzania)", "lcid": "4096"},
    "bho": {"name": "Bhojpuri", "lcid": "4096"},
    "bho_Deva": {"name": "Bhojpuri (Devanagari)", "lcid": "4096"},
    "bho_Deva_IN": {"name": "Bhojpuri (Devanagari India)", "lcid": "4096"},
    "byn": {"name": "Blin", "lcid": "4096"},
    "byn_ER": {"name": "Blin (Eritrea)", "lcid": "4096"},
    "brx": {"name": "Bodo", "lcid": "4096"},
    "brx_IN": {"name": "Bodo (India)", "lcid": "4096"},
    "bs_Cyrl": {"name": "Bosnian (Cyrillic)", "lcid": "25626"},
    "bs_Cyrl_BA": {"name": "Bosnian (Cyrillic Bosnia and Herzegovina)", "lcid": "8218"},
    "bs_Latn": {"name": "Bosnian (Latin)", "lcid": "26650"},
    "bs": {"name": "Bosnian (Latin)", "lcid": "30746"},
    "bs_Latn_BA": {"name": "Bosnian (Latin Bosnia and Herzegovina)", "lcid": "5146"},
    "br": {"name": "Breton", "lcid": "126"},
    "br_FR": {"name": "Breton (France)", "lcid": "1150"},
    "bg": {"name": "Bulgarian", "lcid": "2"},
    "bg_BG": {"name": "Bulgarian (Bulgaria)", "lcid": "1026"},
    "my": {"name": "Burmese", "lcid": "85"},
    "my_MM": {"name": "Burmese (Myanmar)", "lcid": "1109"},
    "ca": {"name": "Catalan", "lcid": "3"},
    "ca_AD": {"name": "Catalan (Andorra)", "lcid": "4096"},
    "ca_FR": {"name": "Catalan (France)", "lcid": "4096"},
    "ca_IT": {"name": "Catalan (Italy)", "lcid": "4096"},
    "ca_ES": {"name": "Catalan (Catalan)", "lcid": "1027"},
    "ceb": {"name": "Cebuano", "lcid": "4096"},
    "ceb_Latn": {"name": "Cebuan (Latin)", "lcid": "4096"},
    "ceb_Latn_PH": {"name": "Cebuan (Latin Philippines)", "lcid": "4096"},
    "tzm_Arab_MA": {"name": "Central Atlas Tamazight (Arabic Morocco)", "lcid": "1119"},
    "tzm_Latn_MA": {"name": "Central Atlas Tamazight (Latin Morocco)", "lcid": "4096"},
    "ku": {"name": "Central Kurdish", "lcid": "146"},
    "ku_Arab": {"name": "Central Kurdish", "lcid": "31890"},
    "ku_Arab_IQ": {"name": "Central Kurdish (Perso-Arabic Iraq)", "lcid": "1170"},
    "ccp": {"name": "Chakma", "lcid": "4096"},
    "ccp_Cakm": {"name": "Chakma (Chakma)", "lcid": "4096"},
    "ccp_Cakm_BD": {"name": "Chakma (Bangladesh)", "lcid": "4096"},
    "ccp_Cakm_IN": {"name": "Chakma (India)", "lcid": "4096"},
    "ce_RU": {"name": "Chechen (Russia)", "lcid": "4096"},
    "chr": {"name": "Cherokee", "lcid": "92"},
    "chr_Cher": {"name": "Cherokee", "lcid": "31836"},
    "chr_Cher_US": {"name": "Cherokee (Cherokee United States)", "lcid": "1116"},
    "cgg": {"name": "Chiga", "lcid": "4096"},
    "cgg_UG": {"name": "Chiga (Uganda)", "lcid": "4096"},
    "zh_Hans": {"name": "Chinese (Simplified)", "lcid": "4"},
    "zh": {"name": "Chinese (Simplified)", "lcid": "30724"},
    "zh_CN": {"name": "Chinese (Simplified PRC)", "lcid": "2052"},
    "zh_SG": {"name": "Chinese (Simplified Singapore)", "lcid": "4100"},
    "zh_Hant": {"name": "Chinese (Traditional)", "lcid": "31748"},
    "zh_HK": {"name": "Chinese (Traditional Hong Kong S.A.R.)", "lcid": "3076"},
    "zh_MO": {"name": "Chinese (Traditional Macao S.A.R.)", "lcid": "5124"},
    "zh_TW": {"name": "Chinese (Traditional Taiwan)", "lcid": "1028"},
    "cu_RU": {"name": "Church Slavic (Russia)", "lcid": "4096"},
    "cv": {"name": "Chuvash", "lcid": "4096"},
    "cv_Cyrl": {"name": "Chuvash (Cyrillic)", "lcid": "4096"},
    "cv_Cyrl_RU": {"name": "Chuvash (Cyrillic Russia)", "lcid": "4096"},
    "swc": {"name": "Congo Swahili", "lcid": "4096"},
    "swc_CD": {"name": "Congo Swahili (Congo DRC)", "lcid": "4096"},
    "kw": {"name": "Cornish", "lcid": "4096"},
    "kw_GB": {"name": "Cornish (United Kingdom)", "lcid": "4096"},
    "co": {"name": "Corsican", "lcid": "131"},
    "co_FR": {"name": "Corsican (France)", "lcid": "1155"},
    "hr": {"name": "Croatian", "lcid": "26"},
    "hr_HR": {"name": "Croatian (Croatia)", "lcid": "1050"},
    "hr_BA": {"name": "Croatian (Latin Bosnia and Herzegovina)", "lcid": "4122"},
    "cs": {"name": "Czech", "lcid": "5"},
    "cs_CZ": {"name": "Czech (Czech Republic)", "lcid": "1029"},
    "da": {"name": "Danish", "lcid": "6"},
    "da_DK": {"name": "Danish (Denmark)", "lcid": "1030"},
    "da_GL": {"name": "Danish (Greenland)", "lcid": "4096"},
    "prs": {"name": "Dari", "lcid": "140"},
    "prs_AF": {"name": "Dari (Afghanistan)", "lcid": "1164"},
    "dv": {"name": "Divehi", "lcid": "101"},
    "dv_MV": {"name": "Divehi (Maldives)", "lcid": "1125"},
    "dua": {"name": "Duala", "lcid": "4096"},
    "dua_CM": {"name": "Duala (Cameroon)", "lcid": "4096"},
    "nl": {"name": "Dutch", "lcid": "19"},
    "nl_AW": {"name": "Dutch (Aruba)", "lcid": "4096"},
    "nl_BE": {"name": "Dutch (Belgium)", "lcid": "2067"},
    "nl_BQ": {"name": "Dutch (Bonaire Sint Eustatius and Saba)", "lcid": "4096"},
    "nl_CW": {"name": "Dutch (Curaçao)", "lcid": "4096"},
    "nl_NL": {"name": "Dutch (Netherlands)", "lcid": "1043"},
    "nl_SX": {"name": "Dutch (Sint Maarten)", "lcid": "4096"},
    "nl_SR": {"name": "Dutch (Suriname)", "lcid": "4096"},
    "dz": {"name": "Dzongkha", "lcid": "4096"},
    "dz_BT": {"name": "Dzongkha (Bhutan)", "lcid": "3153"},
    "ebu": {"name": "Embu", "lcid": "4096"},
    "ebu_KE": {"name": "Embu (Kenya)", "lcid": "4096"},
    "en": {"name": "English", "lcid": "9"},
    "en_AS": {"name": "English (American Samoa)", "lcid": "4096"},
    "en_AI": {"name": "English (Anguilla)", "lcid": "4096"},
    "en_AG": {"name": "English (Antigua and Barbuda)", "lcid": "4096"},
    "en_AU": {"name": "English (Australia)", "lcid": "3081"},
    "en_AT": {"name": "English (Austria)", "lcid": "4096"},
    "en_BS": {"name": "English (Bahamas)", "lcid": "4096"},
    "en_BB": {"name": "English (Barbados)", "lcid": "4096"},
    "en_BE": {"name": "English (Belgium)", "lcid": "4096"},
    "en_BZ": {"name": "English (Belize)", "lcid": "10249"},
    "en_BM": {"name": "English (Bermuda)", "lcid": "4096"},
    "en_BW": {"name": "English (Botswana)", "lcid": "4096"},
    "en_IO": {"name": "English (British Indian Ocean Territory)", "lcid": "4096"},
    "en_VG": {"name": "English (British Virgin Islands)", "lcid": "4096"},
    "en_BI": {"name": "English (Burundi)", "lcid": "4096"},
    "en_CM": {"name": "English (Cameroon)", "lcid": "4096"},
    "en_CA": {"name": "English (Canada)", "lcid": "4105"},
    "en_029": {"name": "English (Caribbean)", "lcid": "9225"},
    "en_KY": {"name": "English (Cayman Islands)", "lcid": "4096"},
    "en_CX": {"name": "English (Christmas Island)", "lcid": "4096"},
    "en_CC": {"name": "English (Cocos [Keeling] Islands)", "lcid": "4096"},
    "en_CK": {"name": "English (Cook Islands)", "lcid": "4096"},
    "en_CY": {"name": "English (Cyprus)", "lcid": "4096"},
    "en_DK": {"name": "English (Denmark)", "lcid": "4096"},
    "en_DM": {"name": "English (Dominica)", "lcid": "4096"},
    "en_ER": {"name": "English (Eritrea)", "lcid": "4096"},
    "en_150": {"name": "English (Europe)", "lcid": "4096"},
    "en_FK": {"name": "English (Falkland Islands)", "lcid": "4096"},
    "en_FI": {"name": "English (Finland)", "lcid": "4096"},
    "en_FJ": {"name": "English (Fiji)", "lcid": "4096"},
    "en_GM": {"name": "English (Gambia)", "lcid": "4096"},
    "en_DE": {"name": "English (Germany)", "lcid": "4096"},
    "en_GH": {"name": "English (Ghana)", "lcid": "4096"},
    "en_GI": {"name": "English (Gibraltar)", "lcid": "4096"},
    "en_GD": {"name": "English (Grenada)", "lcid": "4096"},
    "en_GU": {"name": "English (Guam)", "lcid": "4096"},
    "en_GG": {"name": "English (Guernsey)", "lcid": "4096"},
    "en_GY": {"name": "English (Guyana)", "lcid": "4096"},
    "en_HK": {"name": "English (Hong Kong)", "lcid": "15369"},
    "en_IN": {"name": "English (India)", "lcid": "16393"},
    "en_IE": {"name": "English (Ireland)", "lcid": "6153"},
    "en_IM": {"name": "English (Isle of Man)", "lcid": "4096"},
    "en_IL": {"name": "English (Israel)", "lcid": "4096"},
    "en_JM": {"name": "English (Jamaica)", "lcid": "8201"},
    "en_JE": {"name": "English (Jersey)", "lcid": "4096"},
    "en_KE": {"name": "English (Kenya)", "lcid": "4096"},
    "en_KI": {"name": "English (Kiribati)", "lcid": "4096"},
    "en_LS": {"name": "English (Lesotho)", "lcid": "4096"},
    "en_LR": {"name": "English (Liberia)", "lcid": "4096"},
    "en_MO": {"name": "English (Macao SAR)", "lcid": "4096"},
    "en_MG": {"name": "English (Madagascar)", "lcid": "4096"},
    "en_MW": {"name": "English (Malawi)", "lcid": "4096"},
    "en_MY": {"name": "English (Malaysia)", "lcid": "17417"},
    "en_MV": {"name": "English (Maldives)", "lcid": "4096"},
    "en_MT": {"name": "English (Malta)", "lcid": "4096"},
    "en_MH": {"name": "English (Marshall Islands)", "lcid": "4096"},
    "en_MU": {"name": "English (Mauritius)", "lcid": "4096"},
    "en_FM": {"name": "English (Micronesia)", "lcid": "4096"},
    "en_MS": {"name": "English (Montserrat)", "lcid": "4096"},
    "en_NA": {"name": "English (Namibia)", "lcid": "4096"},
    "en_NR": {"name": "English (Nauru)", "lcid": "4096"},
    "en_NL": {"name": "English (Netherlands)", "lcid": "4096"},
    "en_NZ": {"name": "English (New Zealand)", "lcid": "5129"},
    "en_NG": {"name": "English (Nigeria)", "lcid": "4096"},
    "en_NU": {"name": "English (Niue)", "lcid": "4096"},
    "en_NF": {"name": "English (Norfolk Island)", "lcid": "4096"},
    "en_MP": {"name": "English (Northern Mariana Islands)", "lcid": "4096"},
    "en_PK": {"name": "English (Pakistan)", "lcid": "4096"},
    "en_PW": {"name": "English (Palau)", "lcid": "4096"},
    "en_PG": {"name": "English (Papua New Guinea)", "lcid": "4096"},
    "en_PN": {"name": "English (Pitcairn Islands)", "lcid": "4096"},
    "en_PR": {"name": "English (Puerto Rico)", "lcid": "4096"},
    "en_PH": {"name": "English (Republic of the Philippines)", "lcid": "13321"},
    "en_RW": {"name": "English (Rwanda)", "lcid": "4096"},
    "en_KN": {"name": "English (Saint Kitts and Nevis)", "lcid": "4096"},
    "en_LC": {"name": "English (Saint Lucia)", "lcid": "4096"},
    "en_VC": {"name": "English (Saint Vincent and the Grenadines)", "lcid": "4096"},
    "en_WS": {"name": "English (Samoa)", "lcid": "4096"},
    "en_SC": {"name": "English (Seychelles)", "lcid": "4096"},
    "en_SL": {"name": "English (Sierra Leone)", "lcid": "4096"},
    "en_SG": {"name": "English (Singapore)", "lcid": "18441"},
    "en_SX": {"name": "English (Sint Maarten)", "lcid": "4096"},
    "en_SI": {"name": "English (Slovenia)", "lcid": "4096"},
    "en_SB": {"name": "English (Solomon Islands)", "lcid": "4096"},
    "en_ZA": {"name": "English (South Africa)", "lcid": "7177"},
    "en_SS": {"name": "English (South Sudan)", "lcid": "4096"},
    "en_SH": {"name": "English (St Helena, Ascension, Tristan da Cunha)", "lcid": "4096"},
    "en_SD": {"name": "English (Sudan)", "lcid": "4096"},
    "en_SZ": {"name": "English (Swaziland)", "lcid": "4096"},
    "en_SE": {"name": "English (Sweden)", "lcid": "4096"},
    "en_CH": {"name": "English (Switzerland)", "lcid": "4096"},
    "en_TZ": {"name": "English (Tanzania)", "lcid": "4096"},
    "en_TK": {"name": "English (Tokelau)", "lcid": "4096"},
    "en_TO": {"name": "English (Tonga)", "lcid": "4096"},
    "en_TT": {"name": "English (Trinidad and Tobago)", "lcid": "11273"},
    "en_TC": {"name": "English (Turks and Caicos Islands)", "lcid": "4096"},
    "en_TV": {"name": "English (Tuvalu)", "lcid": "4096"},
    "en_UG": {"name": "English (Uganda)", "lcid": "4096"},
    "en_AE": {"name": "English (United Arab Emirates)", "lcid": "19465"},
    "en_GB": {"name": "English (United Kingdom)", "lcid": "2057"},
    "en_US": {"name": "English (United States)", "lcid": "1033"},
    "en_UM": {"name": "English (US Minor Outlying Islands)", "lcid": "4096"},
    "en_VI": {"name": "English (US Virgin Islands)", "lcid": "4096"},
    "en_VU": {"name": "English (Vanuatu)", "lcid": "4096"},
    "en_001": {"name": "English (World)", "lcid": "4096"},
    "en_ZM": {"name": "English (Zambia)", "lcid": "4096"},
    "en_ZW": {"name": "English (Zimbabwe)", "lcid": "12297"},
    "eo": {"name": "Esperanto", "lcid": "4096"},
    "eo_001": {"name": "Esperanto (World)", "lcid": "4096"},
    "et": {"name": "Estonian", "lcid": "37"},
    "et_EE": {"name": "Estonian (Estonia)", "lcid": "1061"},
    "ee": {"name": "Ewe", "lcid": "4096"},
    "ee_GH": {"name": "Ewe (Ghana)", "lcid": "4096"},
    "ee_TG": {"name": "Ewe (Togo)", "lcid": "4096"},
    "ewo": {"name": "Ewondo", "lcid": "4096"},
    "ewo_CM": {"name": "Ewondo (Cameroon)", "lcid": "4096"},
    "fo": {"name": "Faroese", "lcid": "56"},
    "fo_DK": {"name": "Faroese (Denmark)", "lcid": "4096"},
    "fo_FO": {"name": "Faroese (Faroe Islands)", "lcid": "1080"},
    "fil": {"name": "Filipino", "lcid": "100"},
    "fil_PH": {"name": "Filipino (Philippines)", "lcid": "1124"},
    "fi": {"name": "Finnish", "lcid": "11"},
    "fi_FI": {"name": "Finnish (Finland)", "lcid": "1035"},
    "fr": {"name": "French", "lcid": "12"},
    "fr_DZ": {"name": "French (Algeria)", "lcid": "4096"},
    "fr_BE": {"name": "French (Belgium)", "lcid": "2060"},
    "fr_BJ": {"name": "French (Benin)", "lcid": "4096"},
    "fr_BF": {"name": "French (Burkina Faso)", "lcid": "4096"},
    "fr_BI": {"name": "French (Burundi)", "lcid": "4096"},
    "fr_CM": {"name": "French (Cameroon)", "lcid": "11276"},
    "fr_CA": {"name": "French (Canada)", "lcid": "3084"},
    "fr_029": {"name": "French (Caribbean)", "lcid": "7180"},
    "fr_CF": {"name": "French (Central African Republic)", "lcid": "4096"},
    "fr_TD": {"name": "French (Chad)", "lcid": "4096"},
    "fr_KM": {"name": "French (Comoros)", "lcid": "4096"},
    "fr_CG": {"name": "French (Congo)", "lcid": "4096"},
    "fr_CD": {"name": "French (Congo, DRC)", "lcid": "9228"},
    "fr_CI": {"name": "French (Côte d'Ivoire)", "lcid": "12300"},
    "fr_DJ": {"name": "French (Djibouti)", "lcid": "4096"},
    "fr_GQ": {"name": "French (Equatorial Guinea)", "lcid": "4096"},
    "fr_FR": {"name": "French (France)", "lcid": "1036"},
    "fr_GF": {"name": "French (French Guiana)", "lcid": "4096"},
    "fr_PF": {"name": "French (French Polynesia)", "lcid": "4096"},
    "fr_GA": {"name": "French (Gabon)", "lcid": "4096"},
    "fr_GP": {"name": "French (Guadeloupe)", "lcid": "4096"},
    "fr_GN": {"name": "French (Guinea)", "lcid": "4096"},
    "fr_HT": {"name": "French (Haiti)", "lcid": "15372"},
    "fr_LU": {"name": "French (Luxembourg)", "lcid": "5132"},
    "fr_MG": {"name": "French (Madagascar)", "lcid": "4096"},
    "fr_ML": {"name": "French (Mali)", "lcid": "13324"},
    "fr_MQ": {"name": "French (Martinique)", "lcid": "4096"},
    "fr_MR": {"name": "French (Mauritania)", "lcid": "4096"},
    "fr_MU": {"name": "French (Mauritius)", "lcid": "4096"},
    "fr_YT": {"name": "French (Mayotte)", "lcid": "4096"},
    "fr_MA": {"name": "French (Morocco)", "lcid": "14348"},
    "fr_NC": {"name": "French (New Caledonia)", "lcid": "4096"},
    "fr_NE": {"name": "French (Niger)", "lcid": "4096"},
    "fr_MC": {"name": "French (Principality of Monaco)", "lcid": "6156"},
    "fr_RE": {"name": "French (Reunion)", "lcid": "8204"},
    "fr_RW": {"name": "French (Rwanda)", "lcid": "4096"},
    "fr_BL": {"name": "French (Saint Barthélemy)", "lcid": "4096"},
    "fr_MF": {"name": "French (Saint Martin)", "lcid": "4096"},
    "fr_PM": {"name": "French (Saint Pierre and Miquelon)", "lcid": "4096"},
    "fr_SN": {"name": "French (Senegal)", "lcid": "10252"},
    "fr_SC": {"name": "French (Seychelles)", "lcid": "4096"},
    "fr_CH": {"name": "French (Switzerland)", "lcid": "4108"},
    "fr_SY": {"name": "French (Syria)", "lcid": "4096"},
    "fr_TG": {"name": "French (Togo)", "lcid": "4096"},
    "fr_TN": {"name": "French (Tunisia)", "lcid": "4096"},
    "fr_VU": {"name": "French (Vanuatu)", "lcid": "4096"},
    "fr_WF": {"name": "French (Wallis and Futuna)", "lcid": "4096"},
    "fy": {"name": "Frisian", "lcid": "98"},
    "fy_NL": {"name": "Frisian (Netherlands)", "lcid": "1122"},
    "fur": {"name": "Friulian", "lcid": "4096"},
    "fur_IT": {"name": "Friulian (Italy)", "lcid": "4096"},
    "ff": {"name": "Fulah", "lcid": "103"},
    "ff_Latn": {"name": "Fulah (Latin)", "lcid": "31847"},
    "ff_Latn_BF": {"name": "Fulah (Latin Burkina Faso)", "lcid": "4096"},
    "ff_CM": {"name": "Fulah (Cameroon)", "lcid": "4096"},
    "ff_Latn_CM": {"name": "Fulah (Latin Cameroon)", "lcid": "4096"},
    "ff_Latn_GM": {"name": "Fulah (Latin Gambia)", "lcid": "4096"},
    "ff_Latn_GH": {"name": "Fulah (Latin Ghana)", "lcid": "4096"},
    "ff_GN": {"name": "Fulah (Guinea)", "lcid": "4096"},
    "ff_Latn_GN": {"name": "Fulah (Latin Guinea)", "lcid": "4096"},
    "ff_Latn_GW": {"name": "Fulah (Latin Guinea-Bissau)", "lcid": "4096"},
    "ff_Latn_LR": {"name": "Fulah (Latin Liberia)", "lcid": "4096"},
    "ff_MR": {"name": "Fulah (Mauritania)", "lcid": "4096"},
    "ff_Latn_MR": {"name": "Fulah (Latin Mauritania)", "lcid": "4096"},
    "ff_Latn_NE": {"name": "Fulah (Latin Niger)", "lcid": "4096"},
    "ff_NG": {"name": "Fulah (Nigeria)", "lcid": "1127"},
    "ff_Latn_NG": {"name": "Fulah (Latin Nigeria)", "lcid": "1127"},
    "ff_Latn_SN": {"name": "Fulah (Senegal)", "lcid": "2151"},
    "ff_Latn_SL": {"name": "Fulah (Latin Sierra Leone)", "lcid": "4096"},
    "gl": {"name": "Galician", "lcid": "86"},
    "gl_ES": {"name": "Galician (Galician)", "lcid": "1110"},
    "lg": {"name": "Ganda", "lcid": "4096"},
    "lg_UG": {"name": "Ganda (Uganda)", "lcid": "4096"},
    "ka": {"name": "Georgian", "lcid": "55"},
    "ka_GE": {"name": "Georgian (Georgia)", "lcid": "1079"},
    "de": {"name": "German", "lcid": "7"},
    "de_AT": {"name": "German (Austria)", "lcid": "3079"},
    "de_BE": {"name": "German (Belgium)", "lcid": "4096"},
    "de_DE": {"name": "German (Germany)", "lcid": "1031"},
    "de_IT": {"name": "German (Italy)", "lcid": "4096"},
    "de_LI": {"name": "German (Liechtenstein)", "lcid": "5127"},
    "de_LU": {"name": "German (Luxembourg)", "lcid": "4103"},
    "de_CH": {"name": "German (Switzerland)", "lcid": "2055"},
    "el": {"name": "Greek", "lcid": "8"},
    "el_CY": {"name": "Greek (Cyprus)", "lcid": "4096"},
    "el_GR": {"name": "Greek (Greece)", "lcid": "1032"},
    "kl": {"name": "Greenlandic", "lcid": "111"},
    "kl_GL": {"name": "Greenlandic (Greenland)", "lcid": "1135"},
    "gn": {"name": "Guarani", "lcid": "116"},
    "gn_PY": {"name": "Guarani (Paraguay)", "lcid": "1140"},
    "gu": {"name": "Gujarati", "lcid": "71"},
    "gu_IN": {"name": "Gujarati (India)", "lcid": "1095"},
    "guz": {"name": "Gusii", "lcid": "4096"},
    "guz_KE": {"name": "Gusii (Kenya)", "lcid": "4096"},
    "bgc": {"name": "Haryanvi", "lcid": "4096"},
    "bgc_Deva": {"name": "Haryanvi (Devanagari)", "lcid": "4096"},
    "bgc_Deva_IN": {"name": "Haryanvi (Devanagari India)", "lcid": "4096"},
    "ha": {"name": "Hausa (Latin)", "lcid": "104"},
    "ha_Latn": {"name": "Hausa (Latin)", "lcid": "31848"},
    "ha_Latn_GH": {"name": "Hausa (Latin Ghana)", "lcid": "4096"},
    "ha_Latn_NE": {"name": "Hausa (Latin Niger)", "lcid": "4096"},
    "ha_Latn_NG": {"name": "Hausa (Latin Nigeria)", "lcid": "1128"},
    "haw": {"name": "Hawaiian", "lcid": "117"},
    "haw_US": {"name": "Hawaiian (United States)", "lcid": "1141"},
    "he": {"name": "Hebrew", "lcid": "13"},
    "he_IL": {"name": "Hebrew (Israel)", "lcid": "1037"},
    "hi": {"name": "Hindi", "lcid": "57"},
    "hi_IN": {"name": "Hindi (India)", "lcid": "1081"},
    "hi_Latn": {"name": "Hindi (Latin)", "lcid": "4096"},
    "hi_Latn_IN": {"name": "Hindi (Latin India)", "lcid": "4096"},
    "hu": {"name": "Hungarian", "lcid": "14"},
    "hu_HU": {"name": "Hungarian (Hungary)", "lcid": "1038"},
    "is": {"name": "Icelandic", "lcid": "15"},
    "is_IS": {"name": "Icelandic (Iceland)", "lcid": "1039"},
    "ig": {"name": "Igbo", "lcid": "112"},
    "ig_NG": {"name": "Igbo (Nigeria)", "lcid": "1136"},
    "id": {"name": "Indonesian", "lcid": "33"},
    "id_ID": {"name": "Indonesian (Indonesia)", "lcid": "1057"},
    "ia": {"name": "Interlingua", "lcid": "4096"},
    "ia_FR": {"name": "Interlingua (France)", "lcid": "4096"},
    "ia_001": {"name": "Interlingua (World)", "lcid": "4096"},
    "iu": {"name": "Inuktitut (Latin)", "lcid": "93"},
    "iu_Latn": {"name": "Inuktitut (Latin)", "lcid": "31837"},
    "iu_Latn_CA": {"name": "Inuktitut (Latin Canada)", "lcid": "2141"},
    "iu_Cans": {"name": "Inuktitut (Syllabics)", "lcid": "30813"},
    "iu_Cans_CA": {"name": "Inuktitut (Syllabics Canada)", "lcid": "1117"},
    "ga": {"name": "Irish", "lcid": "60"},
    "ga_IE": {"name": "Irish (Ireland)", "lcid": "2108"},
    "it": {"name": "Italian", "lcid": "16"},
    "it_IT": {"name": "Italian (Italy)", "lcid": "1040"},
    "it_SM": {"name": "Italian (San Marino)", "lcid": "4096"},
    "it_CH": {"name": "Italian (Switzerland)", "lcid": "2064"},
    "it_VA": {"name": "Italian (Vatican City)", "lcid": "4096"},
    "ja": {"name": "Japanese", "lcid": "17"},
    "ja_JP": {"name": "Japanese (Japan)", "lcid": "1041"},
    "jv": {"name": "Javanese", "lcid": "4096"},
    "jv_Latn": {"name": "Javanese (Latin)", "lcid": "4096"},
    "jv_Latn_ID": {"name": "Javanese (Indonesia)", "lcid": "4096"},
    "dyo": {"name": "Jola-Fonyi", "lcid": "4096"},
    "dyo_SN": {"name": "Jola-Fonyi (Senegal)", "lcid": "4096"},
    "kea": {"name": "Kabuverdianu", "lcid": "4096"},
    "kea_CV": {"name": "Kabuverdianu (Cabo Verde)", "lcid": "4096"},
    "kab": {"name": "Kabyle", "lcid": "4096"},
    "kab_DZ": {"name": "Kabyle (Algeria)", "lcid": "4096"},
    "kgp": {"name": "Kaingang", "lcid": "4096"},
    "kgp_Latn": {"name": "Kaingang (Latin)", "lcid": "4096"},
    "kgp_Latn_BR": {"name": "Kaingang (Latin Brazil)", "lcid": "4096"},
    "kkj": {"name": "Kako", "lcid": "4096"},
    "kkj_CM": {"name": "Kako (Cameroon)", "lcid": "4096"},
    "kln": {"name": "Kalenjin", "lcid": "4096"},
    "kln_KE": {"name": "Kalenjin (Kenya)", "lcid": "4096"},
    "kam": {"name": "Kamba", "lcid": "4096"},
    "kam_KE": {"name": "Kamba (Kenya)", "lcid": "4096"},
    "kn": {"name": "Kannada", "lcid": "75"},
    "kn_IN": {"name": "Kannada (India)", "lcid": "1099"},
    "kr_Latn_NG": {"name": "Kanuri (Latin Nigeria)", "lcid": "1137"},
    "ks": {"name": "Kashmiri", "lcid": "96"},
    "ks_Arab": {"name": "Kashmiri (Perso-Arabic)", "lcid": "1120"},
    "ks_Arab_IN": {"name": "Kashmiri (Perso-Arabic India)", "lcid": "4096"},
    "ks_Deva_IN": {"name": "Kashmiri (Devanagari India)", "lcid": "2144"},
    "kk": {"name": "Kazakh", "lcid": "63"},
    "kk_KZ": {"name": "Kazakh (Kazakhstan)", "lcid": "1087"},
    "km": {"name": "Khmer", "lcid": "83"},
    "km_KH": {"name": "Khmer (Cambodia)", "lcid": "1107"},
    "quc": {"name": "K'iche", "lcid": "134"},
    "quc_Latn_GT": {"name": "K'iche' (Latin Guatemala)", "lcid": "1158"},
    "ki": {"name": "Kikuyu", "lcid": "4096"},
    "ki_KE": {"name": "Kikuyu (Kenya)", "lcid": "4096"},
    "rw": {"name": "Kinyarwanda", "lcid": "135"},
    "rw_RW": {"name": "Kinyarwanda (Rwanda)", "lcid": "1159"},
    "sw": {"name": "Kiswahili", "lcid": "65"},
    "sw_KE": {"name": "Kiswahili (Kenya)", "lcid": "1089"},
    "sw_TZ": {"name": "Kiswahili (Tanzania)", "lcid": "4096"},
    "sw_UG": {"name": "Kiswahili (Uganda)", "lcid": "4096"},
    "kok": {"name": "Konkani", "lcid": "87"},
    "kok_IN": {"name": "Konkani (India)", "lcid": "1111"},
    "ko": {"name": "Korean", "lcid": "18"},
    "ko_KR": {"name": "Korean (Korea)", "lcid": "1042"},
    "ko_KP": {"name": "Korean (North Korea)", "lcid": "4096"},
    "khq": {"name": "Koyra Chiini", "lcid": "4096"},
    "khq_ML": {"name": "Koyra Chiini (Mali)", "lcid": "4096"},
    "ses": {"name": "Koyraboro Senni", "lcid": "4096"},
    "ses_ML": {"name": "Koyraboro Senni (Mali)", "lcid": "4096"},
    "nmg": {"name": "Kwasio", "lcid": "4096"},
    "nmg_CM": {"name": "Kwasio (Cameroon)", "lcid": "4096"},
    "ky": {"name": "Kyrgyz", "lcid": "64"},
    "ky_KG": {"name": "Kyrgyz (Kyrgyzstan)", "lcid": "1088"},
    "ku_Arab_IR": {"name": "Kurdish (Perso-Arabic Iran)", "lcid": "4096"},
    "lkt": {"name": "Lakota", "lcid": "4096"},
    "lkt_US": {"name": "Lakota (United States)", "lcid": "4096"},
    "lag": {"name": "Langi", "lcid": "4096"},
    "lag_TZ": {"name": "Langi (Tanzania)", "lcid": "4096"},
    "lo": {"name": "Lao", "lcid": "84"},
    "lo_LA": {"name": "Lao (Lao P.D.R.)", "lcid": "1108"},
    "la_VA": {"name": "Latin (Vatican City)", "lcid": "1142"},
    "lv": {"name": "Latvian", "lcid": "38"},
    "lv_LV": {"name": "Latvian (Latvia)", "lcid": "1062"},
    "ln": {"name": "Lingala", "lcid": "4096"},
    "ln_AO": {"name": "Lingala (Angola)", "lcid": "4096"},
    "ln_CF": {"name": "Lingala (Central African Republic)", "lcid": "4096"},
    "ln_CG": {"name": "Lingala (Congo)", "lcid": "4096"},
    "ln_CD": {"name": "Lingala (Congo DRC)", "lcid": "4096"},
    "lt": {"name": "Lithuanian", "lcid": "39"},
    "lt_LT": {"name": "Lithuanian (Lithuania)", "lcid": "1063"},
    "nds": {"name": "Low German", "lcid": "4096"},
    "nds_DE": {"name": "Low German (Germany)", "lcid": "4096"},
    "nds_NL": {"name": "Low German (Netherlands)", "lcid": "4096"},
    "dsb": {"name": "Lower Sorbian", "lcid": "31790"},
    "dsb_DE": {"name": "Lower Sorbian (Germany)", "lcid": "2094"},
    "lu": {"name": "Luba-Katanga", "lcid": "4096"},
    "lu_CD": {"name": "Luba-Katanga (Congo DRC)", "lcid": "4096"},
    "luo": {"name": "Luo", "lcid": "4096"},
    "luo_KE": {"name": "Luo (Kenya)", "lcid": "4096"},
    "lb": {"name": "Luxembourgish", "lcid": "110"},
    "lb_LU": {"name": "Luxembourgish (Luxembourg)", "lcid": "1134"},
    "luy": {"name": "Luyia", "lcid": "4096"},
    "luy_KE": {"name": "Luyia (Kenya)", "lcid": "4096"},
    "mk": {"name": "Macedonian", "lcid": "47"},
    "mk_MK": {"name": "Macedonian (Former Yugoslav Republic of Macedonia)", "lcid": "1071"},
    "jmc": {"name": "Machame", "lcid": "4096"},
    "jmc_TZ": {"name": "Machame (Tanzania)", "lcid": "4096"},
    "mgh": {"name": "Makhuwa-Meetto", "lcid": "4096"},
    "mgh_MZ": {"name": "Makhuwa-Meetto (Mozambique)", "lcid": "4096"},
    "kde": {"name": "Makonde", "lcid": "4096"},
    "kde_TZ": {"name": "Makonde (Tanzania)", "lcid": "4096"},
    "mg": {"name": "Malagasy", "lcid": "4096"},
    "mg_MG": {"name": "Malagasy (Madagascar)", "lcid": "4096"},
    "ms": {"name": "Malay", "lcid": "62"},
    "ms_BN": {"name": "Malay (Brunei Darussalam)", "lcid": "2110"},
    "ms_MY": {"name": "Malay (Malaysia)", "lcid": "1086"},
    "ml": {"name": "Malayalam", "lcid": "76"},
    "ml_IN": {"name": "Malayalam (India)", "lcid": "1100"},
    "mt": {"name": "Maltese", "lcid": "58"},
    "mt_MT": {"name": "Maltese (Malta)", "lcid": "1082"},
    "gv": {"name": "Manx", "lcid": "4096"},
    "gv_IM": {"name": "Manx (Isle of Man)", "lcid": "4096"},
    "mi": {"name": "Maori", "lcid": "129"},
    "mi_NZ": {"name": "Maori (New Zealand)", "lcid": "1153"},
    "arn": {"name": "Mapudungun", "lcid": "122"},
    "arn_CL": {"name": "Mapudungun (Chile)", "lcid": "1146"},
    "mr": {"name": "Marathi", "lcid": "78"},
    "mr_IN": {"name": "Marathi (India)", "lcid": "1102"},
    "mas": {"name": "Masai", "lcid": "4096"},
    "mas_KE": {"name": "Masai (Kenya)", "lcid": "4096"},
    "mas_TZ": {"name": "Masai (Tanzania)", "lcid": "4096"},
    "mzn_IR": {"name": "Mazanderani (Iran)", "lcid": "4096"},
    "mer": {"name": "Meru", "lcid": "4096"},
    "mer_KE": {"name": "Meru (Kenya)", "lcid": "4096"},
    "mgo": {"name": "Meta'", "lcid": "4096"},
    "mgo_CM": {"name": "Meta' (Cameroon)", "lcid": "4096"},
    "moh": {"name": "Mohawk", "lcid": "124"},
    "moh_CA": {"name": "Mohawk (Mohawk)", "lcid": "1148"},
    "mn": {"name": "Mongolian (Cyrillic)", "lcid": "80"},
    "mn_Cyrl": {"name": "Mongolian (Cyrillic)", "lcid": "30800"},
    "mn_MN": {"name": "Mongolian (Cyrillic Mongolia)", "lcid": "1104"},
    "mn_Mong": {"name": "Mongolian (Traditional Mongolian)", "lcid": "31824"},
    "mn_Mong_CN": {"name": "Mongolian (Traditional Mongolian PRC)", "lcid": "2128"},
    "mn_Mong_MN": {"name": "Mongolian (Traditional Mongolian Mongolia)", "lcid": "3152"},
    "mfe": {"name": "Morisyen", "lcid": "4096"},
    "mfe_MU": {"name": "Morisyen (Mauritius)", "lcid": "4096"},
    "mua": {"name": "Mundang", "lcid": "4096"},
    "mua_CM": {"name": "Mundang (Cameroon)", "lcid": "4096"},
    "nqo": {"name": "N'ko", "lcid": "4096"},
    "nqo_GN": {"name": "N'ko (Guinea)", "lcid": "4096"},
    "naq": {"name": "Nama", "lcid": "4096"},
    "naq_NA": {"name": "Nama (Namibia)", "lcid": "4096"},
    "ne": {"name": "Nepali", "lcid": "97"},
    "ne_IN": {"name": "Nepali (India)", "lcid": "2145"},
    "ne_NP": {"name": "Nepali (Nepal)", "lcid": "1121"},
    "nnh": {"name": "Ngiemboon", "lcid": "4096"},
    "nnh_CM": {"name": "Ngiemboon (Cameroon)", "lcid": "4096"},
    "jgo": {"name": "Ngomba", "lcid": "4096"},
    "jgo_CM": {"name": "Ngomba (Cameroon)", "lcid": "4096"},
    "yrl": {"name": "Nheengatu", "lcid": "4096"},
    "yrl_Latn": {"name": "Nheengatu (Latin)", "lcid": "4096"},
    "yrl_Latn_BR": {"name": "Nheengatu (Latin Brazil)", "lcid": "4096"},
    "yrl_Latn_CO": {"name": "Nheengatu (Latin Colombia)", "lcid": "4096"},
    "yrl_Latn_VE": {"name": "Nheengatu (Latin Venezuela)", "lcid": "4096"},
    "lrc_IQ": {"name": "Northern Luri (Iraq)", "lcid": "4096"},
    "lrc_IR": {"name": "Northern Luri (Iran)", "lcid": "4096"},
    "nd": {"name": "North Ndebele", "lcid": "4096"},
    "nd_ZW": {"name": "North Ndebele (Zimbabwe)", "lcid": "4096"},
    "no": {"name": "Norwegian (Bokmal)", "lcid": "20"},
    "nb": {"name": "Norwegian (Bokmal)", "lcid": "31764"},
    "nb_NO": {"name": "Norwegian Bokmal (Norway)", "lcid": "1044"},
    "nn": {"name": "Norwegian (Nynorsk)", "lcid": "30740"},
    "nn_NO": {"name": "Norwegian Nynorsk (Norway)", "lcid": "2068"},
    "nb_SJ": {"name": "Norwegian Bokmal (Svalbard and Jan Mayen)", "lcid": "4096"},
    "nus": {"name": "Nuer", "lcid": "4096"},
    "nus_SD": {"name": "Nuer (Sudan)", "lcid": "4096"},
    "nus_SS": {"name": "Nuer (South Sudan)", "lcid": "4096"},
    "nyn": {"name": "Nyankole", "lcid": "4096"},
    "nyn_UG": {"name": "Nyankole (Uganda)", "lcid": "4096"},
    "oc": {"name": "Occitan", "lcid": "130"},
    "oc_FR": {"name": "Occitan (France)", "lcid": "1154"},
    "oc_ES": {"name": "Occitan (Spain)", "lcid": "4096"},
    "or": {"name": "Odia", "lcid": "72"},
    "or_IN": {"name": "Oriya (India)", "lcid": "1096"},
    "om": {"name": "Oromo", "lcid": "114"},
    "om_ET": {"name": "Oromo (Ethiopia)", "lcid": "1138"},
    "om_KE": {"name": "Oromo (Kenya)", "lcid": "4096"},
    "os": {"name": "Ossetian", "lcid": "4096"},
    "os_GE": {"name": "Ossetian (Georgia)", "lcid": "4096"},
    "os_RU": {"name": "Ossetian (Russia)", "lcid": "4096"},
    "ps": {"name": "Pashto", "lcid": "99"},
    "ps_AF": {"name": "Pashto (Afghanistan)", "lcid": "1123"},
    "ps_PK": {"name": "Pashto (Pakistan)", "lcid": "4096"},
    "fa": {"name": "Persian", "lcid": "41"},
    "fa_AF": {"name": "Persian (Afghanistan)", "lcid": "4096"},
    "fa_IR": {"name": "Persian (Iran)", "lcid": "1065"},
    "pl": {"name": "Polish", "lcid": "21"},
    "pl_PL": {"name": "Polish (Poland)", "lcid": "1045"},
    "pt": {"name": "Portuguese", "lcid": "22"},
    "pt_AO": {"name": "Portuguese (Angola)", "lcid": "4096"},
    "pt_BR": {"name": "Portuguese (Brazil)", "lcid": "1046"},
    "pt_CV": {"name": "Portuguese (Cabo Verde)", "lcid": "4096"},
    "pt_GQ": {"name": "Portuguese (Equatorial Guinea)", "lcid": "4096"},
    "pt_GW": {"name": "Portuguese (Guinea-Bissau)", "lcid": "4096"},
    "pt_LU": {"name": "Portuguese (Luxembourg)", "lcid": "4096"},
    "pt_MO": {"name": "Portuguese (Macao SAR)", "lcid": "4096"},
    "pt_MZ": {"name": "Portuguese (Mozambique)", "lcid": "4096"},
    "pt_PT": {"name": "Portuguese (Portugal)", "lcid": "2070"},
    "pt_ST": {"name": "Portuguese (Sao Tomé and Príncipe)", "lcid": "4096"},
    "pt_CH": {"name": "Portuguese (Switzerland)", "lcid": "4096"},
    "pt_TL": {"name": "Portuguese (Timor-Leste)", "lcid": "4096"},
    "prg_001": {"name": "Prussian (World)", "lcid": "4096"},
    "qps_ploca": {"name": "Pseudo Language (Pseudo locale for east Asian/complex script localization testing)", "lcid": "1534"},
    "qps_ploc": {"name": "Pseudo Language (Pseudo locale used for localization testing)", "lcid": "1281"},
    "qps_plocm": {"name": "Pseudo Language (Pseudo locale used for localization testing of mirrored locales)", "lcid": "2559"},
    "pa": {"name": "Punjabi", "lcid": "70"},
    "pa_Arab": {"name": "Punjabi", "lcid": "31814"},
    "pa_IN": {"name": "Punjabi (India)", "lcid": "1094"},
    "pa_Arab_PK": {"name": "Punjabi (Pakistan)", "lcid": "2118"},
    "quz": {"name": "Quechua", "lcid": "107"},
    "quz_BO": {"name": "Quechua (Bolivia)", "lcid": "1131"},
    "quz_EC": {"name": "Quechua (Ecuador)", "lcid": "2155"},
    "quz_PE": {"name": "Quechua (Peru)", "lcid": "3179"},
    "raj": {"name": "Rajasthani", "lcid": "4096"},
    "raj_Deva": {"name": "Rajasthani (Devanagari)", "lcid": "4096"},
    "raj_Deva_IN": {"name": "Rajasthani (Devanagari India)", "lcid": "4096"},
    "ksh": {"name": "Ripuarian", "lcid": "4096"},
    "ksh_DE": {"name": "Ripuarian (Germany)", "lcid": "4096"},
    "ro": {"name": "Romanian", "lcid": "24"},
    "ro_MD": {"name": "Romanian (Moldova)", "lcid": "2072"},
    "ro_RO": {"name": "Romanian (Romania)", "lcid": "1048"},
    "rm": {"name": "Romansh", "lcid": "23"},
    "rm_CH": {"name": "Romansh (Switzerland)", "lcid": "1047"},
    "rof": {"name": "Rombo", "lcid": "4096"},
    "rof_TZ": {"name": "Rombo (Tanzania)", "lcid": "4096"},
    "rn": {"name": "Rundi", "lcid": "4096"},
    "rn_BI": {"name": "Rundi (Burundi)", "lcid": "4096"},
    "ru": {"name": "Russian", "lcid": "25"},
    "ru_BY": {"name": "Russian (Belarus)", "lcid": "4096"},
    "ru_KZ": {"name": "Russian (Kazakhstan)", "lcid": "4096"},
    "ru_KG": {"name": "Russian (Kyrgyzstan)", "lcid": "4096"},
    "ru_MD": {"name": "Russian (Moldova)", "lcid": "2073"},
    "ru_RU": {"name": "Russian (Russia)", "lcid": "1049"},
    "ru_UA": {"name": "Russian (Ukraine)", "lcid": "4096"},
    "rwk": {"name": "Rwa", "lcid": "4096"},
    "rwk_TZ": {"name": "Rwa (Tanzania)", "lcid": "4096"},
    "ssy": {"name": "Saho", "lcid": "4096"},
    "ssy_ER": {"name": "Saho (Eritrea)", "lcid": "4096"},
    "sah": {"name": "Sakha", "lcid": "133"},
    "sah_RU": {"name": "Yakut (Russia)", "lcid": "1157"},
    "saq": {"name": "Samburu", "lcid": "4096"},
    "saq_KE": {"name": "Samburu (Kenya)", "lcid": "4096"},
    "smn": {"name": "Sami (Inari)", "lcid": "28731"},
    "smn_FI": {"name": "Sami Inari (Finland)", "lcid": "9275"},
    "smj": {"name": "Sami (Lule)", "lcid": "31803"},
    "smj_NO": {"name": "Sami Lule (Norway)", "lcid": "4155"},
    "smj_SE": {"name": "Sami Lule (Sweden)", "lcid": "5179"},
    "se": {"name": "Sami (Northern)", "lcid": "59"},
    "se_FI": {"name": "Sami Northern (Finland)", "lcid": "3131"},
    "se_NO": {"name": "Sami (Northern Norway)", "lcid": "1083"},
    "se_SE": {"name": "Sami Northern (Sweden)", "lcid": "2107"},
    "sms": {"name": "Sami (Skolt)", "lcid": "29755"},
    "sms_FI": {"name": "Sami Skolt (Finland)", "lcid": "8251"},
    "sma": {"name": "Sami (Southern)", "lcid": "30779"},
    "sma_NO": {"name": "Sami Southern (Norway)", "lcid": "6203"},
    "sma_SE": {"name": "Sami Southern (Sweden)", "lcid": "7227"},
    "sg": {"name": "Sango", "lcid": "4096"},
    "sg_CF": {"name": "Sango (Central African Republic)", "lcid": "4096"},
    "sbp": {"name": "Sangu", "lcid": "4096"},
    "sbp_TZ": {"name": "Sangu (Tanzania)", "lcid": "4096"},
    "sa": {"name": "Sanskrit", "lcid": "79"},
    "sa_IN": {"name": "Sanskrit (India)", "lcid": "1103"},
    "sc": {"name": "Sardinian", "lcid": "4096"},
    "sc_Latn": {"name": "Sardinian (Latin)", "lcid": "4096"},
    "sc_Latn_IT": {"name": "Sardinian (Latin Italy)", "lcid": "4096"},
    "gd": {"name": "Scottish Gaelic", "lcid": "145"},
    "gd_GB": {"name": "Scottish Gaelic (United Kingdom)", "lcid": "1169"},
    "seh": {"name": "Sena", "lcid": "4096"},
    "seh_MZ": {"name": "Sena (Mozambique)", "lcid": "4096"},
    "sr_Cyrl": {"name": "Serbian (Cyrillic)", "lcid": "27674"},
    "sr_Cyrl_BA": {"name": "Serbian (Cyrillic Bosnia and Herzegovina)", "lcid": "7194"},
    "sr_Cyrl_ME": {"name": "Serbian (Cyrillic Montenegro)", "lcid": "12314"},
    "sr_Cyrl_RS": {"name": "Serbian (Cyrillic Serbia)", "lcid": "10266"},
    "sr_Cyrl_CS": {"name": "Serbian (Cyrillic Serbia and Montenegro (Former))", "lcid": "3098"},
    "sr_Latn": {"name": "Serbian (Latin)", "lcid": "28698"},
    "sr": {"name": "Serbian (Latin)", "lcid": "31770"},
    "sr_Latn_BA": {"name": "Serbian (Latin Bosnia and Herzegovina)", "lcid": "6170"},
    "sr_Latn_ME": {"name": "Serbian (Latin Montenegro)", "lcid": "11290"},
    "sr_Latn_RS": {"name": "Serbian (Latin Serbia)", "lcid": "9242"},
    "sr_Latn_CS": {"name": "Serbian (Latin Serbia and Montenegro (Former))", "lcid": "2074"},
    "nso": {"name": "Sesotho sa Leboa", "lcid": "108"},
    "nso_ZA": {"name": "Sesotho sa Leboa (South Africa)", "lcid": "1132"},
    "tn": {"name": "Setswana", "lcid": "50"},
    "tn_BW": {"name": "Setswana (Botswana)", "lcid": "2098"},
    "tn_ZA": {"name": "Setswana (South Africa)", "lcid": "1074"},
    "ksb": {"name": "Shambala", "lcid": "4096"},
    "ksb_TZ": {"name": "Shambala (Tanzania)", "lcid": "4096"},
    "sn": {"name": "Shona", "lcid": "4096"},
    "sn_Latn": {"name": "Shona (Latin)", "lcid": "4096"},
    "sn_Latn_ZW": {"name": "Shona (Latin Zimbabwe)", "lcid": "4096"},
    "sd": {"name": "Sindhi", "lcid": "89"},
    "sd_Arab": {"name": "Sindhi", "lcid": "31833"},
    "sd_Arab_PK": {"name": "Sindhi(Perso-Arabic Pakistan)", "lcid": "2137"},
    "si": {"name": "Sinhala", "lcid": "91"},
    "si_LK": {"name": "Sinhala (Sri Lanka)", "lcid": "1115"},
    "sk": {"name": "Slovak", "lcid": "27"},
    "sk_SK": {"name": "Slovak (Slovakia)", "lcid": "1051"},
    "sl": {"name": "Slovenian", "lcid": "36"},
    "sl_SI": {"name": "Slovenian (Slovenia)", "lcid": "1060"},
    "xog": {"name": "Soga", "lcid": "4096"},
    "xog_UG": {"name": "Soga (Uganda)", "lcid": "4096"},
    "so": {"name": "Somali", "lcid": "119"},
    "so_DJ": {"name": "Somali (Djibouti)", "lcid": "4096"},
    "so_ET": {"name": "Somali (Ethiopia)", "lcid": "4096"},
    "so_KE": {"name": "Somali (Kenya)", "lcid": "4096"},
    "so_SO": {"name": "Somali (Somalia)", "lcid": "1143"},
    "st": {"name": "Sotho", "lcid": "48"},
    "st_ZA": {"name": "Southern Sotho (South Africa)", "lcid": "1072"},
    "nr": {"name": "South Ndebele", "lcid": "4096"},
    "nr_ZA": {"name": "South Ndebele (South Africa)", "lcid": "4096"},
    "st_LS": {"name": "Sesotho (Lesotho)", "lcid": "4096"},
    "es": {"name": "Spanish", "lcid": "10"},
    "es_AR": {"name": "Spanish (Argentina)", "lcid": "11274"},
    "es_BZ": {"name": "Spanish (Belize)", "lcid": "4096"},
    "es_VE": {"name": "Spanish (Bolivarian Republic of Venezuela)", "lcid": "8202"},
    "es_BO": {"name": "Spanish (Bolivia)", "lcid": "16394"},
    "es_BR": {"name": "Spanish (Brazil)", "lcid": "4096"},
    "es_CL": {"name": "Spanish (Chile)", "lcid": "13322"},
    "es_CO": {"name": "Spanish (Colombia)", "lcid": "9226"},
    "es_CR": {"name": "Spanish (Costa Rica)", "lcid": "5130"},
    "es_CU": {"name": "Spanish (Cuba)", "lcid": "23562"},
    "es_DO": {"name": "Spanish (Dominican Republic)", "lcid": "7178"},
    "es_EC": {"name": "Spanish (Ecuador)", "lcid": "12298"},
    "es_SV": {"name": "Spanish (El Salvador)", "lcid": "17418"},
    "es_GQ": {"name": "Spanish (Equatorial Guinea)", "lcid": "4096"},
    "es_GT": {"name": "Spanish (Guatemala)", "lcid": "4106"},
    "es_HN": {"name": "Spanish (Honduras)", "lcid": "18442"},
    "es_419": {"name": "Spanish (Latin America)", "lcid": "22538"},
    "es_MX": {"name": "Spanish (Mexico)", "lcid": "2058"},
    "es_NI": {"name": "Spanish (Nicaragua)", "lcid": "19466"},
    "es_PA": {"name": "Spanish (Panama)", "lcid": "6154"},
    "es_PY": {"name": "Spanish (Paraguay)", "lcid": "15370"},
    "es_PE": {"name": "Spanish (Peru)", "lcid": "10250"},
    "es_PH": {"name": "Spanish (Philippines)", "lcid": "4096"},
    "es_PR": {"name": "Spanish (Puerto Rico)", "lcid": "20490"},
    "es_ES_tradnl": {"name": "Spanish (Spain)", "lcid": "1034"},
    "es_ES": {"name": "Spanish (Spain International Sort)", "lcid": "3082"},
    "es_US": {"name": "Spanish (United States)", "lcid": "21514"},
    "es_UY": {"name": "Spanish (Uruguay)", "lcid": "14346"},
    "zgh": {"name": "Standard Moroccan Tamazight", "lcid": "4096"},
    "zgh_Tfng_MA": {"name": "Standard Morrocan Tamazight (Tifinagh Morocco)", "lcid": "4096"},
    "zgh_Tfng": {"name": "Standard Moroccan Tamazight (Tifinagh)", "lcid": "4096"},
    "ss": {"name": "Swati", "lcid": "4096"},
    "ss_ZA": {"name": "siSwati (South Africa)", "lcid": "4096"},
    "ss_SZ": {"name": "siSwati (Swaziland)", "lcid": "4096"},
    "sv": {"name": "Swedish", "lcid": "29"},
    "sv_AX": {"name": "Swedish (Aland Islands)", "lcid": "4096"},
    "sv_FI": {"name": "Swedish (Finland)", "lcid": "2077"},
    "sv_SE": {"name": "Swedish (Sweden)", "lcid": "1053"},
    "syr": {"name": "Syriac", "lcid": "90"},
    "syr_SY": {"name": "Syriac (Syria)", "lcid": "1114"},
    "shi": {"name": "Tachelhit", "lcid": "4096"},
    "shi_Tfng": {"name": "Tachelhit (Tifinagh)", "lcid": "4096"},
    "shi_Tfng_MA": {"name": "Tachelhit (Tifinagh Morocco)", "lcid": "4096"},
    "shi_Latn": {"name": "Tachelhit (Latin)", "lcid": "4096"},
    "shi_Latn_MA": {"name": "Tachelhit (Latin Morocco)", "lcid": "4096"},
    "dav": {"name": "Taita", "lcid": "4096"},
    "dav_KE": {"name": "Taita (Kenya)", "lcid": "4096"},
    "tg": {"name": "Tajik (Cyrillic)", "lcid": "40"},
    "tg_Cyrl": {"name": "Tajik (Cyrillic)", "lcid": "31784"},
    "tg_Cyrl_TJ": {"name": "Tajik (Cyrillic Tajikistan)", "lcid": "1064"},
    "tzm": {"name": "Tamazight (Latin)", "lcid": "95"},
    "tzm_Latn": {"name": "Tamazight (Latin)", "lcid": "31839"},
    "tzm_Latn_DZ": {"name": "Tamazight (Latin Algeria)", "lcid": "2143"},
    "ta": {"name": "Tamil", "lcid": "73"},
    "ta_IN": {"name": "Tamil (India)", "lcid": "1097"},
    "ta_MY": {"name": "Tamil (Malaysia)", "lcid": "4096"},
    "ta_SG": {"name": "Tamil (Singapore)", "lcid": "4096"},
    "ta_LK": {"name": "Tamil (Sri Lanka)", "lcid": "2121"},
    "twq": {"name": "Tasawaq", "lcid": "4096"},
    "twq_NE": {"name": "Tasawaq (Niger)", "lcid": "4096"},
    "tt": {"name": "Tatar", "lcid": "68"},
    "tt_RU": {"name": "Tatar (Russia)", "lcid": "1092"},
    "te": {"name": "Telugu", "lcid": "74"},
    "te_IN": {"name": "Telugu (India)", "lcid": "1098"},
    "teo": {"name": "Teso", "lcid": "4096"},
    "teo_KE": {"name": "Teso (Kenya)", "lcid": "4096"},
    "teo_UG": {"name": "Teso (Uganda)", "lcid": "4096"},
    "th": {"name": "Thai", "lcid": "30"},
    "th_TH": {"name": "Thai (Thailand)", "lcid": "1054"},
    "bo": {"name": "Tibetan", "lcid": "81"},
    "bo_IN": {"name": "Tibetan (India)", "lcid": "4096"},
    "bo_CN": {"name": "Tibetan (PRC)", "lcid": "1105"},
    "tig": {"name": "Tigre", "lcid": "4096"},
    "tig_ER": {"name": "Tigre (Eritrea)", "lcid": "4096"},
    "ti": {"name": "Tigrinya", "lcid": "115"},
    "ti_ER": {"name": "Tigrinya (Eritrea)", "lcid": "2163"},
    "ti_ET": {"name": "Tigrinya (Ethiopia)", "lcid": "1139"},
    "to": {"name": "Tongan", "lcid": "4096"},
    "to_TO": {"name": "Tongan (Tonga)", "lcid": "4096"},
    "ts": {"name": "Tsonga", "lcid": "49"},
    "ts_ZA": {"name": "Tsonga (South Africa)", "lcid": "1073"},
    "tr": {"name": "Turkish", "lcid": "31"},
    "tr_CY": {"name": "Turkish (Cyprus)", "lcid": "4096"},
    "tr_TR": {"name": "Turkish (Turkey)", "lcid": "1055"},
    "tk": {"name": "Turkmen", "lcid": "66"},
    "tk_TM": {"name": "Turkmen (Turkmenistan)", "lcid": "1090"},
    "uk": {"name": "Ukrainian", "lcid": "34"},
    "uk_UA": {"name": "Ukrainian (Ukraine)", "lcid": "1058"},
    "hsb": {"name": "Upper Sorbian", "lcid": "46"},
    "hsb_DE": {"name": "Upper Sorbian (Germany)", "lcid": "1070"},
    "ur": {"name": "Urdu", "lcid": "32"},
    "ur_IN": {"name": "Urdu (India)", "lcid": "2080"},
    "ur_PK": {"name": "Urdu (Islamic Republic of Pakistan)", "lcid": "1056"},
    "ug": {"name": "Uyghur", "lcid": "128"},
    "ug_CN": {"name": "Uyghur (PRC)", "lcid": "1152"},
    "uz_Arab": {"name": "Uzbek (Perso-Arabic)", "lcid": "4096"},
    "uz_Arab_AF": {"name": "Uzbek (Perso-Arabic Afghanistan)", "lcid": "4096"},
    "uz_Cyrl": {"name": "Uzbek (Cyrillic)", "lcid": "30787"},
    "uz_Cyrl_UZ": {"name": "Uzbek (Cyrillic Uzbekistan)", "lcid": "2115"},
    "uz": {"name": "Uzbek (Latin)", "lcid": "67"},
    "uz_Latn": {"name": "Uzbek (Latin)", "lcid": "31811"},
    "uz_Latn_UZ": {"name": "Uzbek (Latin Uzbekistan)", "lcid": "1091"},
    "vai": {"name": "Vai", "lcid": "4096"},
    "vai_Vaii": {"name": "Vai", "lcid": "4096"},
    "vai_Vaii_LR": {"name": "Vai (Vai Liberia)", "lcid": "4096"},
    "vai_Latn_LR": {"name": "Vai (Latin Liberia)", "lcid": "4096"},
    "vai_Latn": {"name": "Vai (Latin)", "lcid": "4096"},
    "ca_ES_valencia": {"name": "Valencian (Spain)", "lcid": "2051"},
    "ve": {"name": "Venda", "lcid": "51"},
    "ve_ZA": {"name": "Venda (South Africa)", "lcid": "1075"},
    "vi": {"name": "Vietnamese", "lcid": "42"},
    "vi_VN": {"name": "Vietnamese (Vietnam)", "lcid": "1066"},
    "vo": {"name": "Volapük", "lcid": "4096"},
    "vo_001": {"name": "Volapük (World)", "lcid": "4096"},
    "vun": {"name": "Vunjo", "lcid": "4096"},
    "vun_TZ": {"name": "Vunjo (Tanzania)", "lcid": "4096"},
    "wae": {"name": "Walser", "lcid": "4096"},
    "wae_CH": {"name": "Walser (Switzerland)", "lcid": "4096"},
    "cy": {"name": "Welsh", "lcid": "82"},
    "cy_GB": {"name": "Welsh (United Kingdom)", "lcid": "1106"},
    "wal": {"name": "Wolaytta", "lcid": "4096"},
    "wal_ET": {"name": "Wolaytta (Ethiopia)", "lcid": "4096"},
    "wo": {"name": "Wolof", "lcid": "136"},
    "wo_SN": {"name": "Wolof (Senegal)", "lcid": "1160"},
    "xh": {"name": "Xhosa", "lcid": "52"},
    "xh_ZA": {"name": "isiXhosa (South Africa)", "lcid": "1076"},
    "yav": {"name": "Yangben", "lcid": "4096"},
    "yav_CM": {"name": "Yangben (Cameroon)", "lcid": "4096"},
    "ii": {"name": "Yi", "lcid": "120"},
    "ii_CN": {"name": "Yi (PRC)", "lcid": "1144"},
    "yi_001": {"name": "Yiddish (World)", "lcid": "1085"},
    "yo": {"name": "Yoruba", "lcid": "106"},
    "yo_BJ": {"name": "Yoruba (Benin)", "lcid": "4096"},
    "yo_NG": {"name": "Yoruba (Nigeria)", "lcid": "1130"},
    "dje": {"name": "Zarma", "lcid": "4096"},
    "dje_NE": {"name": "Zarma (Niger)", "lcid": "4096"},
    "zu": {"name": "Zulu", "lcid": "53"},
    "zu_ZA": {"name": "isiZulu (South Africa)", "lcid": "1077"},
    "sq_XK": {"name": "Albanian (Kosovo)", "lcid": ""},
    "sw_CD": {"name": "Kiswahili (Congo DRC)", "lcid": ""},
    "ms_SG": {"name": "Malay (Latin Singapore)", "lcid": ""},
}
